dangerouslyAllowAllBuilds: true
blockExoticSubdeps: false
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
